jwt:
  secret: fkdlsem-zjstadasdasdasdasdaspsxmfpdlxm-qkel-qka-t100bm07-intel-evo
  access-token-expiration-ms: 900000       # 15분
  refresh-token-expiration-ms: 604800000   # 7일

spring:
  data:
    redis:
      host: localhost
      port: 6379
